Fixes (#83)
* Work with GSD 2.8.0.

Demonstrate how to use read_log.

* Check for warnings in CI checks.

* Revise notebooks.

1) Use non-deprecated APIs.
2) Use svg matplotlib figure output.
3) Adjust matplotlib figure size (the rendered size changed in a recent matplotlib update)
4) Render fresnel images on a white background.
5) Link to the repository just before every hidden render cell.

* Fix typo.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -89,6 +89,18 @@ jobs:
       env:
         PYTHONPATH: ${{ github.workspace }}/hoomd/build
 
+    # This check is very basic, but we don't want to use `python -W error` as it will also catch any
+    # warnings generated inside nbconvert and its dependencies.
+    - name: Check for warnings
+      run: |
+        has_warnings=0
+        for file in **/*.ipynb
+        do
+          grep Warning $file && echo "::error file=${file}::Has deprecation warnings" && has_warnings=1
+        done
+        exit ${has_warnings}
+      working-directory: notebooks
+
     # notify developers if the scheduled check fails
     - name: Slack notification
       if: ${{ github.event_name == 'schedule' && (failure() || cancelled()) }}
